[package]
name = "git-url-parse"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
honggfuzz = "0.5.54"
git-url-parse = "0.3.1"
[[bin]]
name="git-url-parse"