[package]
name = "fuzzing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
honggfuzz = "0.5.54"
exmex = { git = "https://github.com/bertiqwerty/exmex/" }